[env:waveshare_esp32s3]
platform = espressif32@6.3.2
board = esp32-s3-r8-opi
board_dir = boards
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.filesystem = littlefs
board_build.partitions = default_8MB.csv
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<*> +<buddies/> +<board/> +<input/> +<display/>
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    olikraus/U8g2 @ ^2.36.0
    bitbank2/AnimatedGIF @ ^2.1.0
